name: Container image scan
on: pull_request
jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: aquasecurity/trivy-action@0.33.0
              with:
                image-ref: nginx:1.28.0
                severity: CRITICAL,HIGH
                exit-code: 1